# Generated by Django 4.2 on 2023-08-21 11:18
from django.db import migrations

# Generated by Django 4.2 on 2023-08-18 19:34

from django.db import migrations
import csv

def combine_city(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    City = apps.get_model("properties", "City")
    with open('properties/dz_csv.csv','r') as file :
        csv_reader = csv.reader(file)
        next(csv_reader)
        for index, row in enumerate(csv_reader):
            City.objects.create(name=row[0],lat=row[1],lng=row[2])
            

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_city),
    ]


