# Generated by Django 4.2 on 2023-09-10 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0005_property_created_at_property_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_status',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='borough',
            new_name='email_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cctv',
        ),
        migrations.RemoveField(
            model_name='property',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rental_frequency',
        ),
        migrations.AddField(
            model_name='property',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Commercial', 'Commercial')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PropertiesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('video', models.URLField(max_length=524)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='properties.amenity'),
        ),
    ]
