# Generated by Django 4.2 on 2023-12-03 08:36

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_amenity_rename_property_status_property_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'amenties'},
        ),
        migrations.AlterField(
            model_name='propertiesimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.property_images_filepath, validators=[properties.models.validate_file_size], verbose_name='image'),
        ),
    ]
