# Generated by Django 4.2 on 2024-10-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_diara'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diara',
            new_name='Commune',
        ),
    ]
